<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto

namespace Phluxor\Cluster\ProtoBuf;

use UnexpectedValueException;

/**
 * 配信ステータス
 *
 * Protobuf type <code>cluster.DeliveryStatus</code>
 */
class DeliveryStatus
{
    /**
     * Generated from protobuf enum <code>Delivered = 0;</code>
     */
    const Delivered = 0;
    /**
     * Generated from protobuf enum <code>SubscriberNoLongerReachable = 1;</code>
     */
    const SubscriberNoLongerReachable = 1;
    /**
     * Generated from protobuf enum <code>Timeout = 2;</code>
     */
    const Timeout = 2;
    /**
     * Generated from protobuf enum <code>OtherError = 127;</code>
     */
    const OtherError = 127;

    private static $valueToName = [
        self::Delivered => 'Delivered',
        self::SubscriberNoLongerReachable => 'SubscriberNoLongerReachable',
        self::Timeout => 'Timeout',
        self::OtherError => 'OtherError',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

