<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ゴシップのキーバリューエントリ
 *
 * Generated from protobuf message <code>cluster.GossipKeyValue</code>
 */
class GossipKeyValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes value = 1;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>string value_type_name = 2;</code>
     */
    protected $value_type_name = '';
    /**
     * Generated from protobuf field <code>int64 sequence_number = 3;</code>
     */
    protected $sequence_number = 0;
    /**
     * Generated from protobuf field <code>int64 local_timestamp_unix_milliseconds = 4;</code>
     */
    protected $local_timestamp_unix_milliseconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value
     *     @type string $value_type_name
     *     @type int|string $sequence_number
     *     @type int|string $local_timestamp_unix_milliseconds
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes value = 1;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value_type_name = 2;</code>
     * @return string
     */
    public function getValueTypeName()
    {
        return $this->value_type_name;
    }

    /**
     * Generated from protobuf field <code>string value_type_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValueTypeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->value_type_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sequence_number = 3;</code>
     * @return int|string
     */
    public function getSequenceNumber()
    {
        return $this->sequence_number;
    }

    /**
     * Generated from protobuf field <code>int64 sequence_number = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSequenceNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->sequence_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 local_timestamp_unix_milliseconds = 4;</code>
     * @return int|string
     */
    public function getLocalTimestampUnixMilliseconds()
    {
        return $this->local_timestamp_unix_milliseconds;
    }

    /**
     * Generated from protobuf field <code>int64 local_timestamp_unix_milliseconds = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLocalTimestampUnixMilliseconds($var)
    {
        GPBUtil::checkInt64($var);
        $this->local_timestamp_unix_milliseconds = $var;

        return $this;
    }

}

