<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 1メンバーのゴシップ状態
 *
 * Generated from protobuf message <code>cluster.GossipMemberState</code>
 */
class GossipMemberState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .cluster.GossipKeyValue> values = 1;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $values
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\Cluster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .cluster.GossipKeyValue> values = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>map<string, .cluster.GossipKeyValue> values = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\Cluster\ProtoBuf\GossipKeyValue::class);
        $this->values = $arr;

        return $this;
    }

}

