<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto

namespace Phluxor\Cluster\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TopicActor 初期化メッセージ
 *
 * Generated from protobuf message <code>cluster.PubSubInitialize</code>
 */
class PubSubInitialize extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 idle_timeout_ms = 1;</code>
     */
    protected $idle_timeout_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $idle_timeout_ms
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Cluster\Metadata\Pubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 idle_timeout_ms = 1;</code>
     * @return int|string
     */
    public function getIdleTimeoutMs()
    {
        return $this->idle_timeout_ms;
    }

    /**
     * Generated from protobuf field <code>int64 idle_timeout_ms = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIdleTimeoutMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->idle_timeout_ms = $var;

        return $this;
    }

}

